#ifndef DEM_ENABLECONDID_H_
#define DEM_ENABLECONDID_H_

typedef enum {
    DEM_ENABLE_COND_IGNITION_ON = 0U,
    DEM_ENABLE_COND_COMM_ACTIVE = 1U,
    DEM_ENABLE_COND_ALWAYS      = 2U,
    DEM_ENABLE_COND_NUM
} Dem_EnableCondIdType;

#endif /* DEM_ENABLECONDID_H_ */
