#ifndef DEM_INTERRID_H_
#define DEM_INTERRID_H_

enum {
    DEM_EVENT_ID_NULL = 0,
    MCU_E_CLOCK_FAILURE,
    CANTRCV_E_NO_TRCV_CONTROL,
    CANTP_E_OPER_NOT_SUPPORTED,
    CANTP_E_COMM,
    CANNM_E_CANIF_TRANSMIT_ERROR,
    CANNM_E_NETWORK_TIMEOUT,
    CANIF_TRCV_E_TRANSCEIVER,
    CANIF_E_INVALID_DLC,
    CANIF_STOPPED,
    CANIF_E_FULL_TX_BUFFER,
    CAN_E_TIMEOUT,
    EEP_E_COM_FAILURE,
    FLS_E_ERASE_FAILED,
    FLS_E_WRITE_FAILED,
    FLS_E_READ_FAILED,
    FLS_E_COMPARE_FAILED,
    FLS_E_UNEXPECTED_FLASH_ID,
    LIN_E_TIMEOUT,
    ECUM_E_RAM_CHECK_FAILED,
    ECUM_E_ALL_RUN_REQUESTS_KILLED,
    ECUM_E_CONFIGURATION_DATA_INCONSISTENT,
    PDUR_E_PDU_INSTANCE_LOST,
    PDUR_E_INIT_FAILED,
    WDGM_E_ALIVE_SUPERVISION,
    WDGM_E_SET_MODE,
    DEM_EVENT_ID_LAST_FOR_BSW,
    DEM_EVENT_ID_LAST_VALID_ID = DEM_EVENT_ID_LAST_FOR_BSW
};

#endif /* DEM_INTERRID_H_ */
